apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: flux-recv
spec:
  rules:
  - host: hooks.35.246.75.225.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: flux-recv
          servicePort: 8080
