---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kuber
  namespace: kuber
spec:
  releaseName: kuber
  chart:
    git: git@github.com:t0ster/kuber.git
    path: charts/kuber-stack
    ref: v1.16.5
  values:
    host: kuber.35.246.75.225.nip.io
