---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: zalenium
  namespace: cicd
spec:
  releaseName: zalenium
  chart:
    git: git@github.com:t0ster/zalenium.git
    path: charts/zalenium
    ref: master
  values:
    nodeSelector:
      enabled: true
      key: node-role.kubernetes.io/master
      value: ""
    hub:
      desiredContainers: 1
      resources:
        requests:
          cpu: 200m
      cpuRequest: 100m
