apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgAGMUOM1Rq6KrxuzF6F1ufYQ+LJ/OHBy4p86EsSQbWx0IoiP3irEdOjLHqChebkF36dR+DvgkCB8uyoRCWx4rGWWCN+8K1gUozRsd8x+Xaanylg+t20AfthXu/3zEbng6ujGHEnl4eX+fAAUDvJgBQp9hgEe/ka4ceHzyuSerECAznvMjYc2YQoopbNRk+Mb/0Qjgq0HKl6WstaK/stm3e3tCdQyl+0iQ7OpADHQzS/f29cJQaNIZais7SquvmohQzcpBUq4qBdPeZif4LNrKdUDLELUVsl5TFCnEuGfpSFH8UbWS0aenTeG3EiUKTl9Q8pGCOyinzkiXmYWXASEEIrve8VWYWQiSVH5tgFB1KxZKPwYSkSp/4Seo3GwcUEZzUulpXNL+kHdklr1qUxlsfwKT6QqbpEFLKe001fey5/l4iubE0TYCjT6Gb71oheKkGlpAWeaEDF5ADmZ3bMBHjrvKKt0vuAw5meMLv9Op9tZfh/qY7BMe1BQ3o/aKzq+96Gkd+ErHxB0OpoMEn7uf+iZM1F6m+PveROOqrdXE3EOcKV9QxzfC31MpjQqct31WfN+ULzzZeLCCtRT8W21oLsaqQL4XWpy6jyPOFmJWK+/e+1EVCRKUJElcNlJNxgB6OzVibykijl/nPwxAtltqSw7aQc+mRmdreRl+703dRvLCWz+PtUTcmW7cr7t35GOUBuQCVLLftAePitnxiJjiIpMrmodpwTbxhbGogaSd5wStuOmRO9tlbwdiMRZrfV2/ii0hSgkaL18GoYpogvX+19sp+KAiBgc7fJ0RCgAM0EuIQu08ASMdtcEJJuC8G9a5UdPuHSNc8oLiPbOqE69Nev822L
  template:
    metadata:
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
