---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access-token
  namespace: cicd
spec:
  encryptedData:
    text: AgCcuVfKdgIqkXzImI0leCFQkdGKn/Z/erPcx/u+OA5wRVCUE6norDEjR2uRNobjUy9Aywowcj9+uuWbBUhX3ekUngSkQgVUB9DFcBZoFQxYGzCT4xKeYP5QsM56nuVdqdFhXJEoJUHkSqoN2iyu7WuiEOTDImrPbgaQusCmMC1BOptRiYWNUABpBOjBLvB7vIzmqaNR/jLWINdSKCnT0n8A05kP33ci/YQo2lYlapbEWBMngJA49klSgYWrZCWc1anfnbJgw1AaLb6ZoONNvD9nEmCLbgAYMOAkFRJswFJaVewKjbflwpcplNVyMFClQSpeH9+lmcgRNF/DCzn1qbFKmbUzK3hxkBhuZMHmePqjRvhoX8HlwBX5+vuHU6mBoq005OTJVKKhawE7UbvF8cD9sAqmyNiigRXzET+8JQKoLEmJtDyCp1FL3BUIYkoTEMLyGdHEVevCH8WVBv9Pp5EF5KJCqbI4rtlU3peVbkzCoMEdZ12nHgnDmGwJuvp9YJ1XX+2VD1rhtf6IpYY3odNpvaY3jwFmJTyEdHJMlE/gehetzp7OfzW8xoQ1dRcwk+xaL4vu44+IK84LDh+Qd8pOhzNftIJ06V/tEaD78mghYveB3yZM2EiJtEqG6lNEBQQL+5f7uSK7OiAmmH84iBQqqTYd6DifXuZutI7LZUa+xxcYxkrBxQ8vG8GRVCXri1MISu6oDNJkJWjLfUDBiU9m4/i7iTrBnEi6+I3oGiienwnJv7RKxkDZ
  template:
    metadata:
      annotations:
        jenkins.io/credentials-description: Github Personal Access Token
      creationTimestamp: null
      labels:
        jenkins.io/credentials-type: secretText
      name: github-access-token
      namespace: cicd
    type: Opaque
status: {}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-username-access-token
  namespace: cicd
spec:
  encryptedData:
    password: AgBQaBT9+3cTp0SbI6q8w4sjorek8Ll0TCM1tQLdZtMEgyaQ+DJa0WU9mWxfjGidqWgc13qaVMDDYuUZ05NGiV5HSbTv4BTK3msYIJy7lskEHwOOG7gBhxIpFT4Wrm0rejfALyN+kGi9csDeOZWYwJszj2Fd5S/4yyf7c39TvwN81MKQu7T+8GsSgst6Yq6PPvHkSoSRFvQOsdWWPpdnt7PRLItBemLID7dZgIm5boPRkDItK+dPlapVrevHAA0z4vdYObQ61S8+EQOM9nPzR+XYUEuhGJPBU3gFjilupsP3tQ7DIA+wOasolp+dTswpMe25gpuJu3fJZ6lbXBMX9bJoYPJrcy6IC6x2RRjsxX8F54ZblOgoL874r9ZGamfkd3GEWN29ZsIgAxzPCxVS5Ki3/qR1bE7GkpD5S75+dwmLUowGPoMafBEQDh56rLVbzr5x615at0824kB7I1jW6kFntAe2/BCrqiBhpC/xS30TXFOdJ02U9gCtYa/HzsNeuUQupWggZypXLKettIprLWMQzRHC6kJ1lF3WeeObY/QBvK7FD/QwD6xkiqbLGzw+dkgTRC02Ab2hvzrG5y/OzGko/zjywgeQF2OEoQGuHT0rlPsrSdzGmxAbY5iVl86xDq+R5OTyFWA080gQrmSTZ2OXbkSqhosY+KBY6C0Iwi7862i527vmMYEPtSeSh8ZO/b2dhD0Did6WzYM3ukmJrFa7mIAYsGelrlL9U+OZX1HNyAZGFG7zwd2G
    username: AgCbwtyAkhaQ48v42CVIzLM+/fNHvhWjmFRwS8n11sBJcfqbpPYYMdDwoN5GQxVHBRiVml8OYq0LKj0kmIl3x1p2iIr9KB9SHLxGOs3Wlrb+T4QSHO7ywshGqkd1rIBZEDakCMpyfLvhIFV1Kg6ote2MP/YoBE2tiVjdNYdaWpdpNOsTTUPefTOD7WTLMJTKhSvwnee6DK73VqD6tZY7s80Ce4Mt4OdscH51NpJBpnHlDt8MSIoGFy4Fh91ozKF/n0hRkUAk8MyG77oKQy1/m5SmbgVKNbb8/WMaCUxpFfXyJNSo6HbnumU4oWgZqGuP1pN3XDCSQxaICzlhaH5Hf4tN2O0t6/xirBoARTVmPR86i9RH9V2XphMwsTuUoiojFLad/Jg+HxXne615ip0+sAVv0Mn4chIG00aarcxpcDy355yIOXssQdvrJXEL8sk5HfyHvYgXIUDSy1U6tRKIc/ptl8+arEViHgXxdyyDHzogYGvjCMDzbt+a98Fn5zCUEn/vt4JGYWZR/XXy5nNG0A+iHtvF71vvkUM7AoXoiJbe6amvPfvcRMHjAMpryH1N6uSa1dt17mf3jxDDpQEWhIa4RhhE+QA6+WfQiWdCQ2jG0bza3uBASQ+DcF5l8SQd3W68fqia1tLTCVQT2tn8ydicAQ/IRKbcvXZNLBXWtwWYZFHnbNQUwPwwVbXC27ZPdBD97JCODwM=
  template:
    metadata:
      annotations:
        jenkins.io/credentials-description: Github Username and Personal Access Token
      creationTimestamp: null
      labels:
        jenkins.io/credentials-type: usernamePassword
      name: github-username-access-token
      namespace: cicd
    type: Opaque
status: {}
