apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: jenkins
spec:
  configurationAsCode:
    configurations:
    - name: jenkins
  master:
    plugins:
    - name: blueocean
      version: 1.22.0
    - name: http_request
      version: 1.8.24
    - name: pipeline-utility-steps
      version: 2.5.0
    basePlugins:
    - name: kubernetes
      version: 1.23.3
    - name: workflow-job
      version: "2.36"
    - name: workflow-aggregator
      version: "2.6"
    - name: git
      version: 4.1.1
    - name: job-dsl
      version: "1.76"
    - name: configuration-as-code
      version: "1.35"
    - name: configuration-as-code-support
      version: "1.19"
    - name: kubernetes-credentials-provider
      version: "0.13"
    containers:
    - name: jenkins-master
      image: jenkins/jenkins:lts
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 12
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 80
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 1500m
          memory: 3Gi
        requests:
          cpu: 100m
          memory: 500Mi
  seedJobs:
  - id: jenkins-operator
    targets: "jobs/*.jenkins"
    description: "Jenkins Operator repository"
    repositoryBranch: master
    repositoryUrl: https://github.com/t0ster/kuber-cicd.git
